spring.application.name=yakshagana-portal
spring.datasource.url=jdbc:mysql://localhost:3306/yakshaganadb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username=yaksha
spring.datasource.password=yaksha123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=8085
logging.level.com.yakshagana=DEBUG
